
name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Cache Go modules
      uses: actions/cache@v3
      with:
        path: |
          ~/go/pkg/mod
          ~/.cache/go-build
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Build-DB
      run: docker-compose build

    - name: Create DB
      run: docker-compose up -d --verbose

    - name: Test
      run: go test -v ./...

    - name: Stop and remove containers
      if: always()
      run: docker-compose down

  build: 
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
        
    - name: Build
      run: go build -v projeto-go-testes-main/main.go
